apiVersion: v1
kind: Service
metadata:
  name: ipeer
  labels:
    app: ipeer
spec:
  ports:
    - port: 80
  selector:
    app: ipeer
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ipeer
  labels:
    app: ipeer
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ipeer
        tier: frontend
    spec:
      containers:
      - name: ipeer-app
        image: ubcctlt/ipeer-app
        env:
        - name: IPEER_DB_HOST
          value: ipeer-mysql
        - name: IPEER_DB_USER
          value: ipeer
        - name: IPEER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        - name: IPEER_SESSION_SAVE
          value: database
        ports:
        - containerPort: 9000
          name: ipeer-app
      - name: ipeer-web
        image: ubcctlt/ipeer-web
        env:
        - name: NGINX_FASTCGI_PASS
          value: localhost:9000
        ports:
        - containerPort: 80
          name: ipeer-web
